[versions]
agp = "8.9.1"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
biometric = "1.4.0-alpha03"

composeBom = "2025.04.00"
activityCompose = "1.10.1"
navigation = "2.8.9"

kotlinxSerialization = "1.7.3"
kotlinxCollectionImmutable = "0.3.8"

coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.8.7"

mmkv = "1.3.11"

hilt = "2.52"
hilt-nav-compose = "1.2.0"

glide-compose = "1.0.0-beta01"

paging = "3.3.6"

retrofit = "2.9.0"
logging-interceptor = "4.10.0"
gson = "2.11.0"

splash-screen = "1.1.0-rc01"

recurly = "fde05cadb5"

gemini-ai = "0.7.0"

sql-delight = "2.0.2"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleViewmodelKtx = "2.9.4"
suggestions = "1.0.0"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splash-screen" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleRuntimeKtx" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-collection-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionImmutable" }

mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-nav-compose" }

glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glide-compose" }

paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

recurly = { module = "com.github.DawnHNguyen:recurly-client-android", version.ref = "recurly" }

gemini-ai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "gemini-ai" }

androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }

sql-delight = { module = "app.cash.sqldelight:android-driver", version.ref = "sql-delight" }
sql-delight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sql-delight" }

ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
suggestions = { group = "com.google.assistant.appactions", name = "suggestions", version.ref = "suggestions" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidTest = { id = "com.android.test", version.ref = "agp" }
sql-delight = { id = "app.cash.sqldelight", version.ref = "sql-delight" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
